# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac87c10893b7d80c53f52c95a30257147d7c2613c2858b5e89cf378c679991a7d34adf78d7eb5827992202d9c3e89a4facff30de2f76bea379326aae126a264c

test:
  secret_key_base: 95e5d5121b987880a5cdf569b2d6f688502304974ed2298e9c0bb7ef68db29ffbe44f34d823f918fbadc1ad89544be6df1ad1090a1eef178cd5afbe46c0107e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
